### ISSUE TITLE
Code links don't open in external editor

### ISSUE THREAD

**Issue by AdminCrystal** [OrigamiDev-Pete/TODO_Manager#41]
I am using vscode as my external editor for godot. When I click on the file or line number it doesn't open in anything. Link navigation only works when I use built in editor.

exec flags {project} --goto {file}:{line}:{col} 

Plugin view still works great as I can see the file names and line numbers  in TODO tab.

**Comment by OrigamiDev-Pete** [comment]
Hi,
What version of Todo Manager and Godot are you running? I recently made a change to the external editor code so that might be the problem.

**Comment by AdminCrystal** [comment]
Godot 4.2.2, 
TODO Downloaded from Asset lib
[plugin]

name="Todo Manager"
description="Dock for housing TODO messages."
author="Peter de Vroom"
version="2.2.2"
script="plugin.gd"

I did also try messing with it on my end as well, even for internal editor it doesn't automatically switch me to script tag, but if I add this line of code it will switch to script tab (still switches to script tab when external editor is enabled but not the correct file, nor does it open in vscode). I have provided the one liner here if you want to auto switch to script for users of your plugin

`
func _on_Tree_item_activated() -> void:
	var item : TreeItem
	match tabs.current_tab:
		0:
			item = project_tree.get_selected()
		1: 
			item = current_tree.get_selected()
	if item.get_metadata(0) is Todo:
		var todo : Todo = item.get_metadata(0)
		plugin.get_editor_interface().edit_script(load(todo.script_path), todo.line_number)
		EditorInterface.set_main_screen_editor('Script') # This one
	else:
		var todo_item = item.get_metadata(0)
		plugin.get_editor_interface().edit_script(load(todo_item.script_path))
		EditorInterface.set_main_screen_editor('Script') # This one
`

**Comment by AdminCrystal** [comment]
I also did just download 2.2.3 to see if that works for me and it also doesn't. I created the bare minimum pr example for opening script tab like I mentioned above but it still doesn't help for external editors
https://github.com/OrigamiDev-Pete/TODO_Manager/pull/42

**Comment by OrigamiDev-Pete** [comment]
Thanks for looking into this. Looks like I will revert back to my manual way of opening scripts. Will have to investigate why the `edit_script()` method doesn't open the external editor despite what the docs say.

**Comment by OrigamiDev-Pete** [comment]
This should be solved by bbf2914. Let me know how you go.

**Comment by AdminCrystal** [comment]
Thanks for the quick response and turn around, was not working as is, this pr fixes it on top of your recent commit.

I really appreciate the quick fix on your end.
https://github.com/OrigamiDev-Pete/TODO_Manager/pull/43/files

**Comment by OrigamiDev-Pete** [comment]
On Windows I believe it's preferred to use %USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd rather than the exe because it sets up some environment variables and passes some args to VS Code before launching.

**Comment by AdminCrystal** [comment]
I did for good measure just now test the old branch you just reverted to see if me using code.cmd would work for external editor and it still does not, so that appears to not be the issue with the external editor

**Comment by AdminCrystal** [comment]
but I have switched myself to code.cmd now, so you can close the pr if you feel its unnecessary

**Comment by OrigamiDev-Pete** [comment]
Thanks for checking that out! I'll close that PR for now while the Godot docs recommend using code.cmd.
