### ISSUE TITLE
Current tab showing no results and lists only updated on restart

### ISSUE THREAD

**Issue by dt192** [OrigamiDev-Pete/TODO_Manager#9]
Hi, changes are only showing up on project restart and the current tab only shows the current file name, but no notes that are in it even though they show in the project tab.

**Comment by OrigamiDev-Pete** [comment]
That's odd. Thanks for submitting an issue!
Would you be able to send a screenshot of the current tab and script?
When you say changes only show up on project restart, what changes are you referring to?

**Comment by dt192** [comment]
Hi,
I got the version from Github. I'm not sure why no new notes were showing before without restart, but that part is working ok now in the project tab, but the Current tab is not showing TODOs and I have some errors.

I just did a little testing. The issue seems to be the Current tab is only reading files in your addon directory. If I drop my file in there, they show up fine in current, but if I move it out to the main res folder, it's not read.

`SCRIPT ERROR: get_active_script: Invalid get index 'resource_path' (on base: 'null instance').
          At: res://addons/Todo_Manager/Dock.gd:59
SCRIPT ERROR: build_tree: Invalid call. Nonexistent function 'get_short_path' in base 'Nil'.
          At: res://addons/Todo_Manager/Current.gd:18`

![current](https://user-images.githubusercontent.com/2612048/106074050-1cbee200-6103-11eb-9195-10c460759951.png)

**Comment by OrigamiDev-Pete** [comment]
Thanks for the info. I'll try and find a fix for this as soon as I can.

**Comment by dt192** [comment]
This seems to be the issue:

![extra_slash](https://user-images.githubusercontent.com/2612048/106079173-9effd400-610c-11eb-8a77-e6cd90d63da1.png)

**Comment by OrigamiDev-Pete** [comment]
Thanks for looking into these errors. Hopefully they have been resolved by my two latest commits. Please try out the main branch and let me know how you go.

**Comment by dt192** [comment]
Yes, perfect.

Many thanks.

**Comment by dt192** [comment]
Hey, I just stumble upon `String.plus_file()` which automatically does the check for the extra slash and only adds it if needed.

```
print(dir.get_current_dir() + "/" + file_name)
print(dir.get_current_dir().plus_file(file_name))

res:///new_script.gd
res://new_script.gd
```
There are also some other path related methods that might be of interest, such as...
```
get_base_dir ( )
get_basename ( )
get_extension ( )
get_file ( )
```

**Comment by OrigamiDev-Pete** [comment]
Good find! That `plus_file()` method could clean up that section a bit.

**Comment by auratheenby** [comment]
hi, i noticed the "current" tab is still not displaying any results (godot 4.2, of course). i looked into the code and indeed it's doing the naive thing of just adding a "/" onto the directory path. changing it to use `path_join()` (which is the rename of `plus_file()` from 3.x) works perfectly. i can make a simple PR to fix it.
